Feature/issue feed order incorrect#62
Ebrisoft/Frontend pull request #68
Opened 2019-12-19 14:08 UTC by Gubbsy

Landlords sorted by date created then priority.
Tenants sorted by date created

2019-12-21 21:07 UTC, tobysmith568 requested changes

2019-12-21 21:07 UTC, tobysmith568 commented on src/app/services/api/api-service.abstract.ts
> +  protected baseURI = "https://a0aed793.ngrok.io/api/v1/";
I'm assuming this needs to be reverted?

2019-12-21 21:07 UTC, tobysmith568 commented on src/app/services/pipes/issues/order-by.pipe.ts
> +      return (new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
What format is .createdAt? is it always 20191221T210229Z for example?

2019-12-21 21:07 UTC, tobysmith568 commented on src/app/views/landlord/new-issue/new-issue.page.ts
> -    if (!this.title || !this.content || !this.houseId || !this.priority) {
Wait, does this PR also contain everything from #67 ?

2020-01-02 16:16 UTC, tobysmith568 approved these changes

2020-01-02 16:16 UTC, tobybessant approved these changes

2020-01-02 16:17 UTC, merged