Hotfix/new line support#56
Ebrisoft/Frontend pull request #69
Opened 2019-12-19 14:42 UTC by Gubbsy

To respect white space style="white-space: pre-line" must be set

2019-12-21 21:09 UTC, tobysmith568 requested changes
This PR, like #68, contains all lots of the same changes as #67

2020-01-02 16:20 UTC, tobybessant approved these changes

2020-01-02 16:32 UTC, tobybessant approved these changes

2020-01-02 16:33 UTC, tobysmith568 approved these changes

2020-01-02 16:34 UTC, merged